### ISSUE TITLE
Bugfixes and new Version Tag

### ISSUE THREAD

**Issue by h4cc** [beautiful-docs/beautiful-docs#49]
This is very promising tool and library, that seems to have compelled in progress.

The latest version `1.0.3` from 2013 (!) has some flaws that can be fixed. Anybody interested in this besides the author?

**Comment by h4cc** [comment]
@maximebf Maybe creating a Organization for this project might revive development?

http://fabien.potencier.org/article/75/about-personal-github-accounts

**Comment by maximebf** [comment]
Moved the repo to its own organization
